version: "3.8"

services:

  data_gathering:
    container_name: data_gathering
    build:
      context: ./data-gathering
      dockerfile: Dockerfile
    depends_on:
      - firefox_webdriver
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./flags:/flags
      - pickle_data:/.pickles
    ports:
      - "4443:4444"
    environment:
      - TZ=Europe/Warsaw
    restart: always

  database_manager:
    container_name: database_manager
    build:
      context: ./database-manager
      dockerfile: Dockerfile
    depends_on:
      - data_gathering
      - mysql_database
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./flags:/flags
      - isolated_data:/.data
      - shared_data:/var/lib/mysql-files/
    ports:
      - "3308:3306"
    environment:
      - TZ=Europe/Warsaw
    restart: always

  data_miner:
    container_name: data_miner
    build:
      context: ./data-miner
      dockerfile: Dockerfile
    depends_on:
      - mysql_database
    volumes:
      - ./logs:/logs
      - ./flags:/flags
    ports:
      - "3309:3306"
    environment:
      - TZ=Europe/Warsaw
    restart: always

  node_server:
    container_name: node_server
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mysql_database
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Warsaw
    restart: always

  firefox_webdriver:
    container_name: firefox_webdriver
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
    restart: always

  mysql_database:
    container_name: mysql_database
    image: mysql/mysql-server
    environment:
      - MYSQL_DATABASE=gathering
      - MYSQL_USER=database-manager
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_data:/var/lib/mysql
      - shared_data:/var/lib/mysql-files
    ports:
      - "3307:3306"
    restart: always

volumes:
  pickle_data: null
  isolated_data: null
  shared_data: null
  mysql_data: null
