version: "3.8"

services:

  gathering:
    image: the-gathering
    container_name: data-gathering
    shm_size: 2gb
    depends_on:
      - webdriver
    command: python -u ./main.py
    volumes:
      - ./data:/data
      - ./logs:/logs

  webdriver:
    image: selenium/standalone-firefox
    container_name: firefox-webdriver
    ports:
      - "4444:4444"
