version: "3.8"

services:

  data_gathering:
    container_name: data_gathering
    build:
      context: ./data-gathering
      dockerfile: Dockerfile
    depends_on:
      - firefox_webdriver
    command: python -u ./main.py
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./flags:/flags
      - pickle_data:/.pickles
    ports:
      - "4443:4444"
    environment:
      - TZ=Europe/Warsaw
    restart: always

  database_manager:
    container_name: database_manager
    build:
      context: ./database-manager
      dockerfile: Dockerfile
    depends_on:
      - data_gathering
      - mysql_database
    command: python -u ./main.py
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./flags:/flags
      - isolated_data:/.data
    ports:
      - "3308:3306"
    environment:
      - TZ=Europe/Warsaw
    restart: always

  firefox_webdriver:
    container_name: firefox_webdriver
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
    restart: always

  mysql_database:
    container_name: mysql_database
    image: mysql/mysql-server
    environment:
      MYSQL_DATABASE: gathering
      MYSQL_USER: database-manager
      MYSQL_PASSWORD: pZV3RjEjpZV3RjEj
      MYSQL_ROOT_PASSWORD: pZV3RjEjpZV3RjEj
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always

volumes:
  pickle_data:
  isolated_data:
  mysql_data: