version: "3.8"

services:

  data_gathering:
    container_name: data_gathering
    shm_size: 2gb
    build:
      context: ./data-gathering
      dockerfile: Dockerfile
    depends_on:
      - firefox-webdriver
    command: python -u ./main.py
    volumes:
      - ./data:/data
      - ./logs:/logs
    ports:
      - "4443:4443"
      - "4442:4442"
      - "4441:4441"

  database_manager:
    container_name: database_manager
    build:
      context: ./database-manager
      dockerfile: Dockerfile
    depends_on:
      - data-gathering
    command: python -u ./main.py
    volumes:
      - ./data:/data
      - ./logs:/logs
    restart: always

  firefox_webdriver:
    container_name: firefox_webdriver
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
    restart: always
